#!/usr/bin/env python3
"""
Generate the shared chrome (nav, footer) into every page from data/.

The HTML files remain the real, editable, deployable source. Only the blocks
between marker comments are machine-owned:

    <!-- bba:nav start — generated by tools/sync.py · do not edit -->
    …
    <!-- bba:nav end -->

Usage:
    python3 tools/sync.py --init     # one-time: wrap existing nav/footer in markers
    python3 tools/sync.py            # rewrite managed regions from data/
    python3 tools/sync.py --check    # exit 1 if anything is out of date (no writes)

To change the nav or footer, edit data/apps.json or data/site.json and re-run —
never edit inside a managed region, or --check will fail at push time.

Pure stdlib, Python 3.9 compatible. Run from the repo root.
"""

import os
import re
import sys
import json
from string import Template

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SKIP_DIRS = {"assets", "tools", "templates", "data", ".git", "docs", "_snap"}

REGIONS = ("nav", "footer")
START = ("<!-- bba:%s start — generated by tools/sync.py from data/ "
         "· do not edit by hand -->")
END = "<!-- bba:%s end -->"


# ── data ─────────────────────────────────────────────────────────────────

def load():
    def j(name):
        with open(os.path.join(ROOT, "data", name), encoding="utf-8") as fh:
            return json.load(fh)
    site = j("site.json")
    apps = sorted(j("apps.json")["apps"], key=lambda a: a["order"])
    pages = j("pages.json")["pages"]
    return site, apps, pages


def tpl(name):
    with open(os.path.join(ROOT, "templates", name), encoding="utf-8") as fh:
        return Template(fh.read())


def pages_on_disk():
    out = []
    for dirpath, dirnames, filenames in os.walk(ROOT):
        dirnames[:] = [d for d in dirnames
                       if d not in SKIP_DIRS and not d.startswith(".")]
        for fn in filenames:
            if fn.endswith(".html"):
                out.append(os.path.relpath(os.path.join(dirpath, fn), ROOT))
    press = "press/index.html"
    if os.path.exists(os.path.join(ROOT, press)):
        out.append(press)
    return sorted(set(out))


# ── rendering ────────────────────────────────────────────────────────────

def render_nav(site, apps, page_cfg):
    current = page_cfg.get("nav_current")
    items = []
    for app in apps:
        href = app["paths"]["site"]
        mark = ' aria-current="page"' if href == current else ""
        items.append('        <a href="%s"%s>%s</a>' % (href, mark, app["name"]))
    for sec in site["nav_sections"]:
        mark = ' aria-current="page"' if sec["href"] == current else ""
        items.append('        <a href="%s"%s>%s</a>' % (sec["href"], mark, sec["label"]))
    variant = " site-nav--overlay" if page_cfg.get("nav_variant") == "overlay" else ""
    return tpl("nav.html").substitute(
        nav_variant_class=variant,
        logo=site["logo"],
        site_name=site["name"],
        nav_links="\n".join(items),
    ).rstrip("\n")


def render_footer(site, apps):
    links = ['        <a href="%s">%s</a>' % (a["paths"]["site"], a["name"]) for a in apps]
    links += ['        <a href="%s">%s</a>' % (s["href"], s["label"]) for s in site["nav_sections"]]

    legal = []
    for app in apps:
        for page in app.get("pages", []):
            if page.get("footer_label"):
                legal.append('        <a href="%s">%s</a>'
                             % (page["href"], page["footer_label"]))

    social = []
    for s in site["socials"]:
        social.append(
            '        <a href="%s" target="_blank" rel="%s" aria-label="%s">\n'
            '            <svg viewBox="%s" aria-hidden="true"><path d="%s"/></svg>\n'
            '        </a>' % (s["href"], s["rel"], s["label"], s["viewbox"], s["path"]))

    return tpl("footer.html").substitute(
        site_name=site["name"],
        footer_links="\n".join(links),
        footer_legal="\n".join(legal),
        footer_social="\n".join(social),
        signoff=site["signoff"],
        copyright=site["copyright"],
    ).rstrip("\n")


# ── region surgery ───────────────────────────────────────────────────────

def region_span(html, name, path):
    """(start_idx, end_idx) of the full marked region, or None. Hard-errors on
    an unbalanced pair — a silent skip would reintroduce the staleness this
    whole tool exists to prevent."""
    s = html.find(START % name)
    e = html.find(END % name)
    if s < 0 and e < 0:
        return None
    if s < 0 or e < 0 or e < s:
        raise SystemExit(
            "ERROR: %s has an unbalanced 'bba:%s' marker pair.\n"
            "       Restore both markers or re-run with --init." % (path, name))
    return s, e + len(END % name)


def wrap(name, body):
    return "%s\n%s\n%s" % (START % name, body, END % name)


def init_file(path, html):
    """Wrap the existing nav/footer blocks in markers (one-time migration)."""
    changed = False
    for name, pat, close in (
            ("nav", r'<nav class="site-nav[^"]*">', "</nav>"),
            ("footer", r'<footer class="site-footer">', "</footer>")):
        if region_span(html, name, path):
            continue
        m = re.search(pat, html)
        if not m:
            raise SystemExit("ERROR: %s has no <%s> block to wrap." % (path, name))
        end = html.find(close, m.start())
        if end < 0:
            raise SystemExit("ERROR: %s has an unclosed %s." % (path, close))
        end += len(close)
        html = html[:m.start()] + wrap(name, html[m.start():end]) + html[end:]
        changed = True
    return html, changed


def main():
    args = set(sys.argv[1:])
    do_init = "--init" in args
    check = "--check" in args

    site, apps, pages_cfg = load()
    files = pages_on_disk()

    missing_cfg = [f for f in files if f not in pages_cfg]
    if missing_cfg:
        raise SystemExit("ERROR: no data/pages.json entry for: %s"
                         % ", ".join(missing_cfg))

    footer_html = render_footer(site, apps)
    stale, wrote = [], []

    for rel in files:
        path = os.path.join(ROOT, rel)
        with open(path, encoding="utf-8") as fh:
            html = original = fh.read()

        if do_init:
            html, changed = init_file(path, html)
            if changed and not check:
                with open(path, "w", encoding="utf-8") as fh:
                    fh.write(html)
                wrote.append(rel + " (markers)")
            continue

        spans = {}
        for name in REGIONS:
            span = region_span(html, name, rel)
            if span is None:
                raise SystemExit(
                    "ERROR: %s has no 'bba:%s' markers.\n"
                    "       Run: python3 tools/sync.py --init" % (rel, name))
            spans[name] = span

        new = {"nav": wrap("nav", render_nav(site, apps, pages_cfg[rel])),
               "footer": wrap("footer", footer_html)}

        # replace from the bottom up so earlier offsets stay valid
        for name in sorted(REGIONS, key=lambda n: spans[n][0], reverse=True):
            s, e = spans[name]
            html = html[:s] + new[name] + html[e:]

        if html != original:
            stale.append(rel)
            if not check:
                with open(path, "w", encoding="utf-8") as fh:
                    fh.write(html)
                wrote.append(rel)

    if do_init:
        print("init: wrapped markers in %d file(s)" % len(wrote))
        return 0
    if check:
        if stale:
            print("sync --check FAILED: %d file(s) out of date:" % len(stale))
            for f in stale:
                print("    %s" % f)
            print("\nRun: python3 tools/sync.py")
            print("(If you hand-edited a managed region, move the change into data/ instead.)")
            return 1
        print("✓ sync: all %d pages up to date" % len(files))
        return 0
    if wrote:
        print("sync: updated %d file(s)" % len(wrote))
        for f in wrote:
            print("    %s" % f)
    else:
        print("sync: no changes (%d pages already current)" % len(files))
    return 0


if __name__ == "__main__":
    sys.exit(main())
