#!/usr/bin/env python3
"""
Generate the shared chrome (nav, footer) into every page from data/.

The HTML files remain the real, editable, deployable source. Only the blocks
between marker comments are machine-owned:

    <!-- bba:nav start — generated by tools/sync.py · do not edit -->
    …
    <!-- bba:nav end -->

Usage:
    python3 tools/sync.py --init     # one-time: wrap existing nav/footer in markers
    python3 tools/sync.py            # rewrite managed regions from data/
    python3 tools/sync.py --check    # exit 1 if anything is out of date (no writes)

To change the nav or footer, edit data/apps.json or data/site.json and re-run —
never edit inside a managed region, or --check will fail at push time.

Pure stdlib, Python 3.9 compatible. Run from the repo root.
"""

import os
import re
import sys
import json
from string import Template

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SKIP_DIRS = {"assets", "tools", "templates", "data", ".git", "docs", "_snap"}

REGIONS = ("head", "nav", "footer", "analytics")
START = ("<!-- bba:%s start — generated by tools/sync.py from data/ "
         "· do not edit by hand -->")
END = "<!-- bba:%s end -->"


# ── data ─────────────────────────────────────────────────────────────────

def load():
    def j(name):
        with open(os.path.join(ROOT, "data", name), encoding="utf-8") as fh:
            return json.load(fh)
    site = j("site.json")
    apps = sorted(j("apps.json")["apps"], key=lambda a: a["order"])
    pages = j("pages.json")["pages"]
    return site, apps, pages


def tpl(name):
    with open(os.path.join(ROOT, "templates", name), encoding="utf-8") as fh:
        return Template(fh.read())


def pages_on_disk():
    out = []
    for dirpath, dirnames, filenames in os.walk(ROOT):
        dirnames[:] = [d for d in dirnames
                       if d not in SKIP_DIRS and not d.startswith(".")]
        for fn in filenames:
            if fn.endswith(".html"):
                out.append(os.path.relpath(os.path.join(dirpath, fn), ROOT))
    press = "press/index.html"
    if os.path.exists(os.path.join(ROOT, press)):
        out.append(press)
    return sorted(set(out))


# ── rendering ────────────────────────────────────────────────────────────

def render_nav(site, apps, page_cfg):
    current = page_cfg.get("nav_current")
    items = []
    for app in apps:
        href = app["paths"]["site"]
        mark = ' aria-current="page"' if href == current else ""
        items.append('        <a href="%s"%s>%s</a>' % (href, mark, app["name"]))
    for sec in site["nav_sections"]:
        mark = ' aria-current="page"' if sec["href"] == current else ""
        items.append('        <a href="%s"%s>%s</a>' % (sec["href"], mark, sec["label"]))
    variant = " site-nav--overlay" if page_cfg.get("nav_variant") == "overlay" else ""
    return tpl("nav.html").substitute(
        nav_variant_class=variant,
        logo=site["logo"],
        site_name=site["name"],
        nav_links="\n".join(items),
    ).rstrip("\n")


def render_footer(site, apps):
    links = ['        <a href="%s">%s</a>' % (a["paths"]["site"], a["name"]) for a in apps]
    links += ['        <a href="%s">%s</a>' % (s["href"], s["label"]) for s in site["nav_sections"]]

    legal = []
    for app in apps:
        for page in app.get("pages", []):
            if page.get("footer_label"):
                legal.append('        <a href="%s">%s</a>'
                             % (page["href"], page["footer_label"]))

    social = []
    for s in site["socials"]:
        social.append(
            '        <a href="%s" target="_blank" rel="%s" aria-label="%s">\n'
            '            <svg viewBox="%s" aria-hidden="true"><path d="%s"/></svg>\n'
            '        </a>' % (s["href"], s["rel"], s["label"], s["viewbox"], s["path"]))

    return tpl("footer.html").substitute(
        site_name=site["name"],
        footer_links="\n".join(links),
        footer_legal="\n".join(legal),
        footer_social="\n".join(social),
        signoff=site["signoff"],
        copyright=site["copyright"],
    ).rstrip("\n")


def oxford(names):
    """['a','b','c'] -> 'a, b, and c'"""
    if len(names) == 1:
        return names[0]
    if len(names) == 2:
        return "%s and %s" % tuple(names)
    return "%s, and %s" % (", ".join(names[:-1]), names[-1])


def render_head(site, apps, rel, cfg):
    alt = cfg.get("og_image_alt")
    if alt == "@auto":
        alt = ("%s — Independent iOS apps, built with care. %s."
               % (site["name"], oxford([a["name"] for a in apps])))
    return tpl("head.html").substitute(
        site_name=site["name"],
        title=cfg["title"],
        description=cfg["description"],
        url=cfg["url"],
        og_title=cfg.get("og_title") or cfg["title"],
        og_description=cfg.get("og_description") or cfg["description"],
        og_image=cfg["og_image"],
        og_image_alt=alt,
    ).rstrip("\n")


def write_sitemap(pages_cfg):
    """One url field per page feeds canonical, og:url AND this — so the three
    can never disagree."""
    urls = sorted({c["url"] for c in pages_cfg.values()})
    body = "\n".join("  <url><loc>%s</loc></url>" % u for u in urls)
    xml = ('<?xml version="1.0" encoding="UTF-8"?>\n'
           '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
           '%s\n</urlset>\n' % body)
    path = os.path.join(ROOT, "sitemap.xml")
    old = open(path, encoding="utf-8").read() if os.path.exists(path) else None
    if old != xml:
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(xml)
        return True
    return False


def write_robots(site):
    txt = ("User-agent: *\n"
           "Allow: /\n"
           "\n"
           "# Tooling and data are committed (the host serves everything) but\n"
           "# are not content — keep them out of the index.\n"
           "Disallow: /data/\n"
           "Disallow: /tools/\n"
           "Disallow: /templates/\n"
           "\n"
           "Sitemap: %s/sitemap.xml\n" % site["origin"])
    path = os.path.join(ROOT, "robots.txt")
    old = open(path, encoding="utf-8").read() if os.path.exists(path) else None
    if old != txt:
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(txt)
        return True
    return False


# ── launch status ────────────────────────────────────────────────────────

REVIEW_TEXT = "Coming soon to the App Store"
LIVE_TEXT = "Download on the App Store"


def render_badge(app, badge):
    """The status pill for one app on one page. When the app goes live this
    becomes a real link to the App Store — set status + app_store_url in
    data/apps.json and re-run sync."""
    cls = badge["class"]
    if app["status"] == "live" and app.get("app_store_url"):
        text = badge.get("live_text", LIVE_TEXT)
        return ('<a class="%s" href="%s" target="_blank" rel="noopener">%s</a>'
                % (cls, app["app_store_url"], text))
    text = badge.get("review_text", REVIEW_TEXT)
    return '<div class="%s">%s</div>' % (cls, text)


def render_press_store(app):
    if app["status"] == "live" and app.get("app_store_url"):
        url = app["app_store_url"]
        return ('<tr><th>App Store</th><td><a href="%s" class="lnk" target="_blank" '
                'rel="noopener">%s</a></td></tr>' % (url, url))
    return ('<tr><th>App Store</th><td><span class="pending">'
            'Link added on launch day</span></td></tr>')


def render_press_release(app):
    if app["status"] == "live" and app.get("release_date"):
        return "<tr><th>Release date</th><td>%s</td></tr>" % app["release_date"]
    return ('<tr><th>Release date</th><td><span class="pending">'
            'Pending App Review</span></td></tr>')


def render_status_line(apps):
    """The About page's aggregate sentence, as a full <p> element — never
    hand-count apps again."""
    return '<p class="section-sub">%s</p>' % _status_sentence(apps)


def _status_sentence(apps):
    live = [a for a in apps if a["status"] == "live"]
    if not live:
        n = {1: "It's", 2: "Both", 3: "All three"}.get(len(apps), "All %d" % len(apps))
        return "%s coming soon to the App Store." % n
    if len(live) == len(apps):
        n = {1: "It's", 2: "Both", 3: "All three"}.get(len(apps), "All %d" % len(apps))
        return "%s on the App Store now." % n
    return "%s on the App Store now, %s coming soon." % (
        oxford([a["name"] for a in live]),
        oxford([a["name"] for a in apps if a["status"] != "live"]))


def render_app_region(name, apps, rel):
    """Dispatch a 'bba:<kind>:<slug>' region."""
    kind, _, slug = name.partition(":")
    by_slug = {a["slug"]: a for a in apps}
    if kind == "statusline":
        return render_status_line(apps)
    app = by_slug.get(slug)
    if app is None:
        raise SystemExit("ERROR: %s references unknown app '%s'" % (rel, slug))
    if kind == "badge":
        for b in app.get("badges", []):
            if b["page"] == rel:
                return render_badge(app, b)
        raise SystemExit("ERROR: %s has a badge region for '%s' but apps.json "
                         "declares no badge for this page." % (rel, slug))
    if kind == "pressstore":
        return render_press_store(app)
    if kind == "pressrelease":
        return render_press_release(app)
    raise SystemExit("ERROR: %s has unknown region kind '%s'" % (rel, kind))


def render_analytics(site):
    """Cookieless analytics tag, or nothing at all.

    Deliberately opt-in and provider-agnostic: the studio's whole pitch is
    'no tracking', so this must be trivial to inspect and trivial to remove.
    Cloudflare already reports server-side stats with no script — prefer that."""
    cfg = site.get("analytics") or {}
    provider, token = cfg.get("provider"), cfg.get("token")
    if not provider or not token:
        return "<!-- no analytics -->"
    if provider == "cloudflare":
        return ('<script defer src="https://static.cloudflareinsights.com/beacon.min.js" '
                'data-cf-beacon=\'{"token": "%s"}\'></script>' % token)
    if provider == "goatcounter":
        return ('<script data-goatcounter="https://%s.goatcounter.com/count" '
                'async src="//gc.zgo.at/count.js"></script>' % token)
    raise SystemExit("ERROR: unknown analytics provider %r in data/site.json" % provider)


# ── region surgery ───────────────────────────────────────────────────────

def region_span(html, name, path):
    """(start_idx, end_idx) of the full marked region, or None. Hard-errors on
    an unbalanced pair — a silent skip would reintroduce the staleness this
    whole tool exists to prevent."""
    s = html.find(START % name)
    e = html.find(END % name)
    if s < 0 and e < 0:
        return None
    if s < 0 or e < 0 or e < s:
        raise SystemExit(
            "ERROR: %s has an unbalanced 'bba:%s' marker pair.\n"
            "       Restore both markers or re-run with --init." % (path, name))
    return s, e + len(END % name)


def wrap(name, body):
    return "%s\n%s\n%s" % (START % name, body, END % name)


def init_file(path, html):
    """Wrap the existing nav/footer blocks in markers (one-time migration)."""
    changed = False
    for name, pat, close in (
            ("head", r'<meta charset=', '<link rel="stylesheet" href="/assets/site.css">'),
            ("nav", r'<nav class="site-nav[^"]*">', "</nav>"),
            ("footer", r'<footer class="site-footer">', "</footer>")):
        if region_span(html, name, path):
            continue
        m = re.search(pat, html)
        if not m:
            raise SystemExit("ERROR: %s has no <%s> block to wrap." % (path, name))
        end = html.find(close, m.start())
        if end < 0:
            raise SystemExit("ERROR: %s has an unclosed %s." % (path, close))
        end += len(close)
        html = html[:m.start()] + wrap(name, html[m.start():end]) + html[end:]
        changed = True

    # analytics has no existing markup to wrap — create an empty region
    if not region_span(html, "analytics", path):
        i = html.rfind("</body>")
        if i < 0:
            raise SystemExit("ERROR: %s has no </body>." % path)
        html = html[:i] + wrap("analytics", "<!-- no analytics -->") + "\n" + html[i:]
        changed = True
    return html, changed


def main():
    args = set(sys.argv[1:])
    do_init = "--init" in args
    check = "--check" in args

    site, apps, pages_cfg = load()
    files = pages_on_disk()

    missing_cfg = [f for f in files if f not in pages_cfg]
    if missing_cfg:
        raise SystemExit("ERROR: no data/pages.json entry for: %s"
                         % ", ".join(missing_cfg))

    footer_html = render_footer(site, apps)
    stale, wrote = [], []

    for rel in files:
        path = os.path.join(ROOT, rel)
        with open(path, encoding="utf-8") as fh:
            html = original = fh.read()

        if do_init:
            html, changed = init_file(path, html)
            if changed and not check:
                with open(path, "w", encoding="utf-8") as fh:
                    fh.write(html)
                wrote.append(rel + " (markers)")
            continue

        spans = {}
        for name in REGIONS:
            span = region_span(html, name, rel)
            if span is None:
                raise SystemExit(
                    "ERROR: %s has no 'bba:%s' markers.\n"
                    "       Run: python3 tools/sync.py --init" % (rel, name))
            spans[name] = span

        new = {"head": wrap("head", render_head(site, apps, rel, pages_cfg[rel])),
               "nav": wrap("nav", render_nav(site, apps, pages_cfg[rel])),
               "footer": wrap("footer", footer_html),
               "analytics": wrap("analytics", render_analytics(site))}

        # A nested or overlapping region would silently eat surrounding markup
        # when spans are spliced. Refuse to proceed.
        marks = [(m.start(), m.group(1), m.group(2)) for m in
                 re.finditer(r"<!-- bba:([a-z0-9:-]+) (start|end)", html)]
        depth, stack = 0, []
        for pos, nm, kind in marks:
            if kind == "start":
                if depth:
                    raise SystemExit(
                        "ERROR: %s has a nested region: 'bba:%s' opens inside "
                        "'bba:%s'. Regions must not overlap." % (rel, nm, stack[-1]))
                stack.append(nm); depth += 1
            else:
                if not stack or stack[-1] != nm:
                    raise SystemExit("ERROR: %s has mismatched region markers "
                                     "near 'bba:%s end'." % (rel, nm))
                stack.pop(); depth -= 1
        if stack:
            raise SystemExit("ERROR: %s has unclosed region 'bba:%s'." % (rel, stack[-1]))

        # per-app regions: bba:badge:<slug>, bba:pressstore:<slug>, …
        for extra in sorted(set(re.findall(
                r"<!-- bba:((?:badge|pressstore|pressrelease|statusline)"
                r"(?::[a-z0-9-]+)?) start", html))):
            span = region_span(html, extra, rel)
            if span:
                spans[extra] = span
                new[extra] = wrap(extra, render_app_region(extra, apps, rel))

        # replace from the bottom up so earlier offsets stay valid
        for name in sorted(spans, key=lambda n: spans[n][0], reverse=True):
            s, e = spans[name]
            html = html[:s] + new[name] + html[e:]

        if html != original:
            stale.append(rel)
            if not check:
                with open(path, "w", encoding="utf-8") as fh:
                    fh.write(html)
                wrote.append(rel)

    if do_init:
        print("init: wrapped markers in %d file(s)" % len(wrote))
        return 0

    side = []
    if not check:
        if write_sitemap(pages_cfg):
            side.append("sitemap.xml")
        if write_robots(site):
            side.append("robots.txt")
    else:
        import io
        want_map = sorted({c["url"] for c in pages_cfg.values()})
        sp = os.path.join(ROOT, "sitemap.xml")
        have = re.findall(r"<loc>([^<]+)</loc>",
                          open(sp, encoding="utf-8").read()) if os.path.exists(sp) else []
        if sorted(have) != want_map:
            stale.append("sitemap.xml")
        if not os.path.exists(os.path.join(ROOT, "robots.txt")):
            stale.append("robots.txt")
    if check:
        if stale:
            print("sync --check FAILED: %d file(s) out of date:" % len(stale))
            for f in stale:
                print("    %s" % f)
            print("\nRun: python3 tools/sync.py")
            print("(If you hand-edited a managed region, move the change into data/ instead.)")
            return 1
        print("✓ sync: all %d pages up to date" % len(files))
        return 0
    for f in side:
        wrote.append(f)
    if wrote:
        print("sync: updated %d file(s)" % len(wrote))
        for f in wrote:
            print("    %s" % f)
    else:
        print("sync: no changes (%d pages already current)" % len(files))
    return 0


if __name__ == "__main__":
    sys.exit(main())
